# Generated by Django 4.2.16 on 2024-11-22 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=150)),
                ('year_of_study', models.PositiveIntegerField(blank=True, help_text='Current year of study (e.g., 1, 2, 3, etc.)', null=True)),
                ('location', models.CharField(blank=True, help_text='City or region where the student is currently based', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='A short bio or description of the student')),
                ('photo', models.URLField(blank=True, help_text='Profile photo of the student', null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='universities.university')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
