# Generated by Django 4.2.16 on 2024-11-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.URLField(blank=True, default='images/default-student.jpeg', help_text='Profile photo of the student'),
        ),
    ]
