# Generated by Django 4.2.16 on 2024-12-03 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='accounts.profile'),
        ),
    ]
