# Generated by Django 4.2.16 on 2024-12-03 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0003_student_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='accounts.profile'),
            preserve_default=False,
        ),
    ]
