# Generated by Django 4.2.16 on 2024-11-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.URLField(blank=True, help_text='Profile photo of the student', null=True),
        ),
    ]
