# Generated by Django 4.2.16 on 2024-12-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user_profile',
        ),
    ]
