# Generated by Django 4.2.16 on 2024-12-04 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0005_remove_student_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.OneToOneField(default=1, help_text='The profile associated with this student', on_delete=django.db.models.deletion.CASCADE, related_name='student', to='accounts.profile'),
            preserve_default=False,
        ),
    ]
