# Generated by Django 4.2.16 on 2024-12-11 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0010_message_parent_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, help_text='A short bio for you as a student', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.CharField(help_text='City or region where you are currently based', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.PositiveIntegerField(default=1, help_text='Current year of study (e.g., 1, 2, 3, etc.)'),
            preserve_default=False,
        ),
    ]
