# Generated by Django 4.2.16 on 2024-12-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_bio_alter_student_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.PositiveIntegerField(),
        ),
    ]
