# Generated by Django 4.2.16 on 2024-12-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_student_bio_alter_student_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.PositiveIntegerField(error_messages={'min_value': 'Year of study must be a positive number.'}),
        ),
    ]
