# Generated by Django 4.2.16 on 2024-12-11 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_rename_photo_student_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='photo_url',
            new_name='photo',
        ),
    ]
