# Generated by Django 4.2.16 on 2024-12-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_student_average_rating_student_total_ratings_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_ratings',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
