# Generated by Django 4.2.16 on 2024-12-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_student_average_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
