# Generated by Django 4.2.16 on 2024-12-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_alter_student_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='average_rating',
            new_name='avg_rating',
        ),
    ]
