# Generated by Django 4.2.16 on 2024-12-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_rename_average_rating_student_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='avg_rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
