# Generated by Django 4.2.16 on 2024-12-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
