# Generated by Django 4.2.16 on 2024-11-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='logo_url',
            field=models.URLField(blank=True, help_text="Link to the university's logo image", null=True),
        ),
    ]
