# Generated by Django 4.2.16 on 2024-11-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='year_established',
            field=models.PositiveIntegerField(blank=True, help_text='Year the university was established', null=True),
        ),
    ]
