# Generated by Django 4.2.16 on 2024-12-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_alter_university_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the university', null=True),
        ),
    ]
