# Generated by Django 4.2.16 on 2024-12-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_alter_university_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='description',
        ),
    ]
